//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.07 at 08:37:39 PM FET 
//


package com.epam.te.task04.entity_jaxb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Parameters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Parameters">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="favourite_number" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="tariffing" type="{http://www.epam.com.tariff/tariff}Tarrifing_type"/>
 *         &lt;element name="price_for_connection" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Parameters", propOrder = {
    "favouriteNumber",
    "tariffing",
    "priceForConnection"
})
public class Parameters {

    @XmlElement(name = "favourite_number", required = true)
    protected BigDecimal favouriteNumber;
    @XmlElement(required = true)
    protected TarrifingType tariffing;
    @XmlElement(name = "price_for_connection", required = true)
    protected BigDecimal priceForConnection;

    /**
     * Gets the value of the favouriteNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFavouriteNumber() {
        return favouriteNumber;
    }

    /**
     * Sets the value of the favouriteNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFavouriteNumber(BigDecimal value) {
        this.favouriteNumber = value;
    }

    /**
     * Gets the value of the tariffing property.
     * 
     * @return
     *     possible object is
     *     {@link TarrifingType }
     *     
     */
    public TarrifingType getTariffing() {
        return tariffing;
    }

    /**
     * Sets the value of the tariffing property.
     * 
     * @param value
     *     allowed object is
     *     {@link TarrifingType }
     *     
     */
    public void setTariffing(TarrifingType value) {
        this.tariffing = value;
    }

    /**
     * Gets the value of the priceForConnection property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPriceForConnection() {
        return priceForConnection;
    }

    /**
     * Sets the value of the priceForConnection property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPriceForConnection(BigDecimal value) {
        this.priceForConnection = value;
    }

}
